### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by ApatheticSloth** [XeramHosting/The-Epitome#4]
**Describe the bug:**
Enchanting table conflict between Quark and Apotheosis. instead of the apoth enchanting table it converts on placement to quarks Matrix enchanting table which is un-useable.

**To Reproduce:**
1. craft enchanting table
2. (notice its from apotheosis)
3. Place table
4. (gets changed to Matrix enchanting table from quark)

**Expected behavior:**
an enchanting table that works..?

**Pack Version:**
0.8

**Comment by Alyssalove27** [comment]
Matrix enchanting is disabled on the client, but most likely still enabled in the server, preventing both from working actually.

Tested in singleplayer, Apotheosis table stays Apotheosis and works, so the issue is on the server.

The fix would be to set the Matrix enchanting config to false on server-side.
